/// Describe a FlutterMotion composition in JSON and build it at runtime.
///
/// The kit is a vocabulary of scenes; this is that vocabulary made
/// serialisable. A document is data, so it can be written by a designer, sent
/// by a server, generated by a model, or edited by a tool that never compiles
/// anything -- and it renders through exactly the same widgets and the same
/// deterministic frame function as a composition written in Dart.
///
/// ```dart
/// final MotionDocument document = MotionDocument.parse(jsonString);
/// final Composition composition = document.toComposition(data: report);
/// ```
library;

export 'src/document.dart'
    show MotionDocument, currentDocumentVersion, knownNodeTypes;
export 'src/errors.dart' show SchemaException, SchemaProblem;
export 'src/node.dart' show MotionNode, NodeType, ScopedSpec, SpecList;
export 'src/scope.dart' show DataScope, MotionScope, knownFilters;
export 'src/values.dart'
    show namedAlignments, namedCurves, namedFits, paletteRoles;
