/// Build a FlutterMotion composition from a JSON document.
///
/// The kit is a vocabulary of scenes; this is that vocabulary made
/// serialisable. A document is data, so it can be written by a designer, sent
/// by a server, generated by a model, or edited by a tool that never compiles
/// anything -- and it renders through exactly the same widgets and the same
/// deterministic frame function as a composition written in Dart.
///
/// ```dart
/// final MotionDocument document = MotionDocument.parse(jsonString);
/// final Composition composition = document.toComposition(data: report);
/// ```
///
/// The *format* -- the node vocabulary, the binding language, and every check
/// a document has to pass -- lives in `fluttermotion_schema`, which has no
/// Flutter dependency. Validating a document therefore needs neither this
/// package nor an engine. Everything public there is re-exported here, so a
/// renderer needs only this one import.
library;

export 'package:fluttermotion_schema/fluttermotion_schema.dart';

export 'src/document.dart' show MotionDocument, sceneTransition;
export 'src/motion_scope.dart' show MotionScope;
export 'src/node.dart'
    show
        MotionNodeBuilding,
        NodeBuilder,
        NodeWidget,
        ScopedSpecBuilding,
        builderFor,
        registerBuilder,
        unbuildableNodeTypes;
export 'src/values.dart'
    show
        basePalette,
        namedAlignments,
        namedAxes,
        namedCrossAxis,
        namedCurves,
        namedFits,
        namedKitCrossAxis,
        namedMainAxis,
        namedMainAxisSize,
        namedStackFits,
        namedTextAligns,
        namedWeights,
        roleColour,
        roleSize;
