import 'dart:io';

import 'args.dart';
import 'cli_error.dart';

/// Where a generated entry point lives, and what it says.
///
/// A JSON document cannot be rendered on its own: a composition is Flutter
/// code, and the render host is a build of *your project* -- that is what
/// carries the fonts, assets and plugins the document refers to. So the
/// document path becomes a two-line entry point in the project, and everything
/// downstream is the ordinary path.
///
/// Generated under `.dart_tool/` rather than `lib/`: it is a build artefact,
/// it is regenerated on every invocation, and it should never turn up in a
/// diff.
class DocumentEntry {
  const DocumentEntry(this.projectDir);

  final Directory projectDir;

  Directory get _dir =>
      Directory('${projectDir.absolute.path}/.dart_tool/fluttermotion');

  /// Writes a render host for [documentPath] and returns its project-relative
  /// path, ready to hand to `--entry`.
  String writeRenderEntry({required String documentPath, String? dataPath}) =>
      _write('document_render.dart', '''
// GENERATED by `fluttermotion render`. Edit the document, not this file.
import 'package:fluttermotion_json/host.dart';

void main(List<String> args) => documentRenderMain(
      args,
      documentPath: r'${_absolute(documentPath)}',${_dataArg(dataPath)}
    );
''');

  /// Writes a preview host for [documentPath].
  String writePreviewEntry({required String documentPath, String? dataPath}) =>
      _write('document_preview.dart', '''
// GENERATED by `fluttermotion preview`. Edit the document, not this file.
import 'package:fluttermotion_json/host.dart';

void main() => documentPreviewMain(
      documentPath: r'${_absolute(documentPath)}',${_dataArg(dataPath)}
      projectPath: r'${projectDir.absolute.path}',
    );
''');

  String _dataArg(String? dataPath) =>
      dataPath == null ? '' : "\n      dataPath: r'${_absolute(dataPath)}',";

  String _absolute(String path) => absolutePath(path);

  String _write(String name, String source) {
    _dir.createSync(recursive: true);
    File('${_dir.path}/$name').writeAsStringSync(source);
    return '.dart_tool/fluttermotion/$name';
  }

  /// Fails early if the project cannot import what the entry point needs.
  ///
  /// Otherwise the first sign of trouble is a compile error from inside a
  /// generated file the author has never seen.
  void requireDependency() {
    final File pubspec = File('${projectDir.absolute.path}/pubspec.yaml');
    if (!pubspec.existsSync()) {
      throw CliError('No pubspec.yaml in ${projectDir.absolute.path}');
    }
    if (!pubspec.readAsStringSync().contains('fluttermotion_json')) {
      throw CliError(
        'This project does not depend on fluttermotion_json, which is what '
        'reads a document.\n\n'
        'Add it to pubspec.yaml:\n'
        '  dependencies:\n'
        '    fluttermotion_json: ^0.1.0\n',
      );
    }
  }
}

/// The document a command was pointed at, if any.
///
/// Accepted as a positional (`fluttermotion render reel.json`) or as
/// `--document reel.json`, because both read naturally and neither is worth
/// forcing on anyone.
String? documentPathFrom(List<String> rest, String? option) {
  if (option != null) return option;
  for (final String token in rest) {
    if (token.endsWith('.json')) return token;
  }
  return null;
}


/// Absolute, because the host's working directory is not something the CLI
/// controls -- a shard is spawned by the CLI, and a preview by `flutter run`,
/// and the two do not agree on where they start.
String absolutePath(String path) =>
    Uri.file(File(path).absolute.path).normalizePath().toFilePath();

/// What a command needs to build and drive a host: an entry point, and the
/// arguments every invocation of the resulting binary carries.
class HostTarget {
  const HostTarget({required this.entryPoint, this.hostArgs = const <String>[]});

  final String entryPoint;
  final List<String> hostArgs;
}

/// Resolves the host a command should run: the project's own entry point, or
/// a generated one for the document it was pointed at.
///
/// The document is passed on argv as well as baked into the generated entry
/// point. Baking it in alone would make `--no-build` quietly lie: the reused
/// binary carries yesterday's path, so `fluttermotion render other.json
/// --no-build` would render the wrong reel and say the right name. Passing it
/// every time also means one built host serves every document in a project,
/// which is the difference between a two-minute edit loop and an instant one.
HostTarget hostTargetFor(CliArgs args, Directory projectDir) {
  // The host hides itself while it renders, because nothing it draws goes to
  // the screen. Watching it is occasionally what you want, and the flag has to
  // survive to every host invocation to be worth having.
  final List<String> showWindow =
      args.flag('show-window') ? <String>['--show-window'] : <String>[];

  final String? document =
      documentPathFrom(args.rest, args.optional('document'));
  if (document == null) {
    return HostTarget(
      entryPoint: args.value('entry', 'lib/render_main.dart'),
      hostArgs: showWindow,
    );
  }
  if (!File(document).existsSync()) {
    throw CliError('No document at $document');
  }
  final String? data = args.optional('data');
  if (data != null && !File(data).existsSync()) {
    throw CliError('No data file at $data');
  }
  final DocumentEntry entry = DocumentEntry(projectDir)..requireDependency();
  return HostTarget(
    entryPoint: entry.writeRenderEntry(documentPath: document, dataPath: data),
    hostArgs: <String>[
      '--document', absolutePath(document),
      if (data != null) ...<String>['--data', absolutePath(data)],
      ...showWindow,
    ],
  );
}
