import 'errors.dart';
import 'names.dart';
import 'scope.dart';

/// Reads one JSON object, recording what is wrong rather than throwing.
///
/// Every getter takes the key rather than the value so it can name the exact
/// path in a problem: `scenes[2].child.bars[0].value`, not "a number was
/// expected somewhere". A document is usually written by hand or generated by
/// something that got a detail wrong, and the path is the whole difference
/// between a fixable error and a shrug.
class Reader {
  Reader(this.json, this.path, this.problems);

  final Map<String, Object?> json;
  final String path;
  final Problems problems;

  Object? raw(String key) => json[key];

  bool has(String key) => json.containsKey(key) && json[key] != null;

  String at(String key) => child(path, key);

  /// Complains about any key this node does not understand.
  ///
  /// Silently ignoring `titel: "..."` means a typo renders an empty title and
  /// the author goes looking in the wrong place.
  void rejectUnknownKeys(Set<String> known) {
    for (final String key in json.keys) {
      if (!known.contains(key)) {
        // `type` is in the known set but is not a property anyone sets by
        // choice, so listing it in the suggestion is noise.
        final List<String> named =
            known.where((String k) => k != 'type').toList()..sort();
        problems.add(
          at(key),
          'unknown property "$key"; this node accepts ${named.join(', ')}',
        );
      }
    }
  }

  String? string(String key, {bool required = false}) {
    final Object? value = json[key];
    if (value == null) {
      if (required) problems.add(at(key), 'is required');
      return null;
    }
    if (value is String) {
      // A binding in any string, not only in an animated number: `{{ period |
      // shout }}` in a headline renders as nothing at all, which is the least
      // debuggable failure the format has.
      if (isBinding(value)) checkFilters(value, at(key), problems);
      return value;
    }
    problems.add(at(key), 'must be a string, got ${_kind(value)}');
    return null;
  }

  /// A plain number, no animation and no binding: sizes the schema depends on.
  num? plainNumber(String key, {bool required = false}) {
    final Object? value = json[key];
    if (value == null) {
      if (required) problems.add(at(key), 'is required');
      return null;
    }
    if (value is num) return value;
    problems.add(at(key), 'must be a number, got ${_kind(value)}');
    return null;
  }

  int? plainInt(String key, {bool required = false}) {
    final num? value = plainNumber(key, required: required);
    if (value == null) return null;
    if (value is int) return value;
    if (value == value.roundToDouble()) return value.round();
    problems.add(at(key), 'must be a whole number, got $value');
    return null;
  }

  bool? boolean(String key) {
    final Object? value = json[key];
    if (value == null) return null;
    if (value is bool) return value;
    if (isBinding(value)) return null;
    problems.add(at(key), 'must be true or false, got ${_kind(value)}');
    return null;
  }

  /// One of a fixed set of names.
  String? oneOf(String key, Set<String> allowed, {bool required = false}) {
    final String? value = string(key, required: required);
    if (value == null || isBinding(value)) return value;
    if (allowed.contains(value)) return value;
    problems.add(
      at(key),
      '"$value" is not one of ${(allowed.toList()..sort()).join(', ')}',
    );
    return null;
  }

  /// Checks an animatable number and hands back the spec for build time.
  Object? animated(String key, {bool required = false}) {
    final Object? value = json[key];
    if (value == null) {
      if (required) problems.add(at(key), 'is required');
      return null;
    }
    checkAnimated(value, at(key), problems);
    return value;
  }

  Object? colour(String key, {bool required = false}) {
    final Object? value = json[key];
    if (value == null) {
      if (required) problems.add(at(key), 'is required');
      return null;
    }
    checkColour(value, at(key), problems);
    return value;
  }

  Object? insets(String key) {
    final Object? value = json[key];
    if (value == null) return null;
    checkInsets(value, at(key), problems);
    return value;
  }

  /// An asset path, checked for the shapes that must not leave the project.
  ///
  /// A document is a thing a server can send to an app, so `src` is untrusted
  /// input: without this, `../../../etc/passwd` is a valid template.
  String? source(String key, {bool required = false}) {
    final String? value = string(key, required: required);
    if (value == null || isBinding(value)) return value;
    if (value.startsWith('/') || value.contains('..')) {
      problems.add(
        at(key),
        '"$value" leaves the project directory; a source must be a relative '
        'path with no "..".',
      );
      return null;
    }
    return value;
  }
}

String _kind(Object? value) => switch (value) {
  null => 'null',
  String() => 'a string',
  num() => 'a number',
  bool() => 'a boolean',
  List<Object?>() => 'a list',
  Map<Object?, Object?>() => 'an object',
  _ => value.runtimeType.toString(),
};

/// Checks a number that may be a literal, a binding, keyframes, or a spring.
void checkAnimated(Object? value, String path, Problems problems) {
  if (value is num) return;
  if (value is String) {
    _checkBindingString(value, path, problems);
    return;
  }
  if (value is! Map<String, Object?>) {
    problems.add(
      path,
      'must be a number, a "{{ }}" binding, or an object with "keyframes" '
      'or "spring", got ${_kind(value)}',
    );
    return;
  }

  final Reader reader = Reader(value, path, problems);
  if (value.containsKey('keyframes')) {
    reader.rejectUnknownKeys(<String>{'keyframes', 'ease', 'delay'});
    _checkKeyframes(value['keyframes'], child(path, 'keyframes'), problems);
    reader.oneOf('ease', curveNames);
    reader.plainInt('delay');
  } else if (value.containsKey('spring')) {
    reader.rejectUnknownKeys(<String>{'spring'});
    final Object? spec = value['spring'];
    if (spec is! Map<String, Object?>) {
      problems.add(child(path, 'spring'), 'must be an object');
      return;
    }
    Reader(spec, child(path, 'spring'), problems)
      ..rejectUnknownKeys(<String>{
        'from',
        'to',
        'delay',
        'mass',
        'stiffness',
        'damping',
        'velocity',
      })
      ..plainNumber('from')
      ..plainNumber('to')
      ..plainInt('delay')
      ..plainNumber('mass')
      ..plainNumber('stiffness')
      ..plainNumber('damping')
      ..plainNumber('velocity');
  } else {
    problems.add(path, 'must have either "keyframes" or "spring"');
  }
}

void _checkKeyframes(Object? value, String path, Problems problems) {
  if (value is! List<Object?> || value.length < 2) {
    problems.add(path, 'must be a list of at least two [frame, value] pairs');
    return;
  }
  num? previousFrame;
  for (int i = 0; i < value.length; i++) {
    final Object? pair = value[i];
    if (pair is! List<Object?> ||
        pair.length != 2 ||
        pair[0] is! num ||
        pair[1] is! num) {
      problems.add(index(path, i), 'must be a [frame, value] pair of numbers');
      continue;
    }
    final num frame = pair[0]! as num;
    // Interpolation needs a strictly increasing input range, and a document
    // that gives one out of order would otherwise trip an assertion deep in
    // the framework with no idea which keyframe caused it.
    if (previousFrame != null && frame <= previousFrame) {
      problems.add(
        index(path, i),
        'frame $frame does not come after $previousFrame; keyframes must be '
        'in increasing frame order',
      );
    }
    previousFrame = frame;
  }
}

void _checkBindingString(String value, String path, Problems problems) {
  if (!isBinding(value)) {
    problems.add(path, '"$value" is neither a number nor a "{{ }}" binding');
    return;
  }
  checkFilters(value, path, problems);
}

/// Reports any `{{ x | nope }}` naming a filter this package does not have.
void checkFilters(String value, String path, Problems problems) {
  for (final String filter in filtersIn(value)) {
    if (!knownFilters.contains(filter)) {
      problems.add(
        path,
        'unknown filter "$filter"; known filters are '
        '${(knownFilters.toList()..sort()).join(', ')}',
      );
    }
  }
}

void checkColour(Object? value, String path, Problems problems) {
  if (value is! String) {
    problems.add(path, 'must be a colour string, got ${_kind(value)}');
    return;
  }
  if (isBinding(value)) return;
  if (paletteRoles.contains(value)) return;
  if (parseHex(value) != null) return;
  problems.add(
    path,
    '"$value" is not a colour; use #RRGGBB, #AARRGGBB, or one of '
    '${(paletteRoles.toList()..sort()).join(', ')}',
  );
}

void checkInsets(Object? value, String path, Problems problems) {
  if (value is num) return;
  if (value is List<Object?>) {
    if ((value.length == 2 || value.length == 4) &&
        value.every((Object? v) => v is num)) {
      return;
    }
    problems.add(
      path,
      'must be [horizontal, vertical] or [left, top, right, bottom]',
    );
    return;
  }
  if (value is Map<String, Object?>) {
    Reader(value, path, problems)
      ..rejectUnknownKeys(<String>{
        'left',
        'top',
        'right',
        'bottom',
        'horizontal',
        'vertical',
        'all',
      })
      ..plainNumber('left')
      ..plainNumber('top')
      ..plainNumber('right')
      ..plainNumber('bottom')
      ..plainNumber('horizontal')
      ..plainNumber('vertical')
      ..plainNumber('all');
    return;
  }
  problems.add(path, 'must be a number, a list, or an object of edges');
}

/// `#RRGGBB` or `#AARRGGBB` as an ARGB integer, or null if it is neither.
///
/// Returns the integer rather than a colour so that validation and the
/// document's stored theme both stay free of `dart:ui`.
int? parseHex(String value) {
  if (!value.startsWith('#')) return null;
  final String digits = value.substring(1);
  if (digits.length != 6 && digits.length != 8) return null;
  final int? parsed = int.tryParse(digits, radix: 16);
  if (parsed == null) return null;
  return digits.length == 6 ? 0xFF000000 | parsed : parsed;
}
