import 'errors.dart';
import 'reader.dart';
import 'scope.dart';

/// One kind of node a document may contain, and what it accepts.
///
/// Registered rather than switched on, so the vocabulary is a value the
/// package can also *report* -- an editor can ask what exists and what each
/// one accepts, and validation gets the list of legal keys for free instead of
/// every node repeating it.
///
/// There is no builder here. A node type is a statement about a document, not
/// about widgets: `fluttermotion_json` holds a builder per name and refuses to
/// register one for a name this package has never heard of, which is what
/// keeps the two halves from drifting apart.
class NodeType {
  const NodeType({
    required this.name,
    this.properties = const <String>{},
    this.slots = const <String>{},
    this.lists = const <String>{},
    this.specs = const <String, void Function(Reader reader)>{},
    this.validate,
    this.parentData = false,
  });

  final String name;

  /// Scalar property keys.
  final Set<String> properties;

  /// Keys holding one child node.
  final Set<String> slots;

  /// Keys holding a list of child nodes, or a `repeat` over one.
  final Set<String> lists;

  /// Keys holding a list of plain objects rather than nodes -- chart data.
  ///
  /// Each carries the check for one element, so a bar with a string where its
  /// value goes is caught at parse time like anything else. Without it chart
  /// data would be the one part of a document nothing validated, which is also
  /// the part most likely to be generated by a script.
  final Map<String, void Function(Reader reader)> specs;

  /// Per-key checks beyond "is this key allowed".
  final void Function(Reader reader)? validate;

  /// Whether this node must sit *directly* under its parent widget.
  ///
  /// True for `expanded`, which is parent data: a `Flex` reads `Expanded` off
  /// its own children list, and one element of indirection makes the flex
  /// factor disappear. Such a node is built eagerly instead of getting an
  /// element of its own, which is only safe because its properties are plain
  /// numbers -- nothing it reads depends on the frame.
  final bool parentData;

  Set<String> get knownKeys => <String>{
    'type',
    ...properties,
    ...slots,
    ...lists,
    ...specs.keys,
  };
}

/// Every node type this package understands, by name.
///
/// Populated by the `register*Schema` calls; [DocumentSpec] makes sure they
/// have run before anything parses.
final Map<String, NodeType> nodeRegistry = <String, NodeType>{};

void registerNode(NodeType type) => nodeRegistry[type.name] = type;

/// A validated node, ready to build.
///
/// Properties stay as raw JSON: the value of `opacity` may be a number, a
/// binding, or a keyframe track, and which one it is does not change until the
/// frame it is evaluated on. Structure -- children, repeats -- is resolved at
/// parse time, because a mistake there is a mistake in the document rather
/// than in the data.
///
/// Nothing here knows what a widget is. `fluttermotion_json` adds that in an
/// extension, so the tree a validator walks and the tree a renderer builds are
/// the same tree, parsed once.
class MotionNode {
  MotionNode({
    required this.type,
    required this.props,
    required this.path,
    required this.slots,
    required this.lists,
    required this.specs,
  });

  final NodeType type;
  final Map<String, Object?> props;

  /// Where this node sits in the document, for error messages.
  final String path;

  final Map<String, MotionNode> slots;
  final Map<String, ChildList> lists;
  final Map<String, SpecList> specs;

  Object? operator [](String key) => props[key];

  /// A named enum value, already known valid from parse time.
  T? named<T>(String key, Map<String, T> table) => table[props[key]];
}

// ---------------------------------------------------------------------------
// Child lists
// ---------------------------------------------------------------------------

/// A list of children, either written out or repeated over data.
///
/// Which of the two it is settles at parse time; how many items a repeat
/// produces does not settle until the data arrives.
class ChildList {
  ChildList.fixed(this.nodes) : over = null, template = null;

  ChildList.repeated(this.over, this.template) : nodes = const <MotionNode>[];

  final List<MotionNode> nodes;
  final String? over;
  final MotionNode? template;

  bool get repeats => over != null;

  /// The nodes to build, each with the scope its bindings resolve in.
  List<ScopedNode> resolve(DataScope scope) {
    if (over == null) {
      return <ScopedNode>[
        for (final MotionNode node in nodes) ScopedNode(node, scope),
      ];
    }
    final Object? source = scope.resolve(over!);
    if (source is! List<Object?>) return const <ScopedNode>[];
    return <ScopedNode>[
      for (int i = 0; i < source.length; i++)
        ScopedNode(template!, scope.forItem(source[i], i)),
    ];
  }
}

/// One node from a [ChildList], and what its bindings mean.
class ScopedNode {
  const ScopedNode(this.node, this.scope);

  final MotionNode node;
  final DataScope scope;
}

/// A list of plain objects, either written out or repeated over data.
///
/// The same machinery as [ChildList] for things that are not widgets: chart
/// data, mostly. Keeping them the same shape is what lets a document say
/// `repeat` in both places and mean the same thing.
class SpecList {
  SpecList.fixed(this.items) : over = null, template = null;

  SpecList.repeated(this.over, this.template) : items = const <Object?>[];

  final String? over;
  final Map<String, Object?>? template;
  final List<Object?> items;

  bool get repeats => over != null;

  /// The objects to build from, each with the scope its bindings resolve in.
  List<ScopedSpec> resolve(DataScope scope) {
    if (over == null) {
      return <ScopedSpec>[
        for (final Object? item in items)
          if (item is Map<String, Object?>) ScopedSpec(item, scope),
      ];
    }
    final Object? source = scope.resolve(over!);
    if (source is! List<Object?>) return const <ScopedSpec>[];
    return <ScopedSpec>[
      for (int i = 0; i < source.length; i++)
        ScopedSpec(template!, scope.forItem(source[i], i)),
    ];
  }
}

/// One object from a [SpecList], and what its bindings mean.
class ScopedSpec {
  const ScopedSpec(this.json, this.scope);

  final Map<String, Object?> json;
  final DataScope scope;
}

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

/// Turns one JSON value into a node, recording anything wrong along the way.
///
/// Returns null on a problem rather than throwing, so a document with three
/// mistakes reports three rather than the first.
MotionNode? parseNode(Object? json, String path, Problems problems) {
  if (json is! Map<String, Object?>) {
    problems.add(path, 'must be an object with a "type"');
    return null;
  }

  final Object? name = json['type'];
  if (name is! String) {
    problems.add(child(path, 'type'), 'is required and must be a string');
    return null;
  }
  final NodeType? type = nodeRegistry[name];
  if (type == null) {
    problems.add(
      child(path, 'type'),
      '"$name" is not a node type; known types are '
      '${(nodeRegistry.keys.toList()..sort()).join(', ')}',
    );
    return null;
  }

  final Reader reader = Reader(json, path, problems);
  reader.rejectUnknownKeys(type.knownKeys);
  type.validate?.call(reader);

  final Map<String, MotionNode> slots = <String, MotionNode>{};
  for (final String key in type.slots) {
    if (json[key] == null) continue;
    final MotionNode? parsed = parseNode(json[key], child(path, key), problems);
    if (parsed != null) slots[key] = parsed;
  }

  final Map<String, ChildList> lists = <String, ChildList>{};
  for (final String key in type.lists) {
    if (json[key] == null) continue;
    final ChildList? parsed = _parseChildren(
      json[key],
      child(path, key),
      problems,
    );
    if (parsed != null) lists[key] = parsed;
  }

  final Map<String, SpecList> specs = <String, SpecList>{};
  for (final MapEntry<String, void Function(Reader)> entry
      in type.specs.entries) {
    if (json[entry.key] == null) continue;
    final SpecList? parsed = _parseSpecs(
      json[entry.key],
      child(path, entry.key),
      problems,
      entry.value,
    );
    if (parsed != null) specs[entry.key] = parsed;
  }

  return MotionNode(
    type: type,
    props: json,
    path: path,
    slots: slots,
    lists: lists,
    specs: specs,
  );
}

ChildList? _parseChildren(Object? json, String path, Problems problems) {
  if (json is List<Object?>) {
    final List<MotionNode> nodes = <MotionNode>[];
    for (int i = 0; i < json.length; i++) {
      final MotionNode? parsed = parseNode(json[i], index(path, i), problems);
      if (parsed != null) nodes.add(parsed);
    }
    return ChildList.fixed(nodes);
  }
  final _RepeatSpec? repeat = _parseRepeat(json, path, problems);
  if (repeat == null) return null;
  final MotionNode? template = parseNode(
    repeat.template,
    child(path, 'as'),
    problems,
  );
  return template == null ? null : ChildList.repeated(repeat.over, template);
}

SpecList? _parseSpecs(
  Object? json,
  String path,
  Problems problems,
  void Function(Reader reader) validate,
) {
  if (json is List<Object?>) {
    for (int i = 0; i < json.length; i++) {
      final Object? item = json[i];
      if (item is! Map<String, Object?>) {
        problems.add(index(path, i), 'must be an object');
        continue;
      }
      validate(Reader(item, index(path, i), problems));
    }
    return SpecList.fixed(json);
  }
  final _RepeatSpec? repeat = _parseRepeat(json, path, problems);
  if (repeat == null) return null;
  if (repeat.template is! Map<String, Object?>) {
    problems.add(child(path, 'as'), 'must be an object');
    return null;
  }
  final Map<String, Object?> template =
      repeat.template! as Map<String, Object?>;
  validate(Reader(template, child(path, 'as'), problems));
  return SpecList.repeated(repeat.over, template);
}

class _RepeatSpec {
  const _RepeatSpec(this.over, this.template);

  final String over;
  final Object? template;
}

_RepeatSpec? _parseRepeat(Object? json, String path, Problems problems) {
  if (json is! Map<String, Object?>) {
    problems.add(
      path,
      'must be a list, or a {"repeat": "<data path>", "as": ...} object',
    );
    return null;
  }
  final Reader reader = Reader(json, path, problems)
    ..rejectUnknownKeys(<String>{'repeat', 'as'});
  final String? over = reader.string('repeat', required: true);
  if (json['as'] == null) {
    problems.add(child(path, 'as'), 'is required alongside "repeat"');
    return null;
  }
  return over == null ? null : _RepeatSpec(over, json['as']);
}
