import 'dart:io';

/// Why a sandboxed macOS app cannot host a render.
///
/// The render host is a macOS build of the user's own application, so it is
/// signed with that application's entitlements. Most shipping apps enable App
/// Sandbox, and App Sandbox forbids executing a binary outside the app bundle
/// -- which is exactly what the host does when it spawns ffmpeg. The render
/// therefore dies at the encode step with a bare `Operation not permitted`,
/// after a full build has already been paid for.
///
/// Reading the entitlements first turns that into an answer before the build
/// rather than a stack trace after it.
abstract final class SandboxCheck {
  /// The entitlements a release build is signed with.
  static File entitlementsFile(Directory projectDir) => File(
    // Normalised, because this path is printed. `--project .` and an absolute
    // project directory both reach here, and joining either naively produces
    // a `/./` in the middle of the one line the reader is meant to act on.
    Uri.file(
      '${projectDir.path}/macos/Runner/Release.entitlements',
    ).normalizePath().toFilePath(),
  );

  /// A complaint to show the user, or null if nothing is wrong.
  ///
  /// Silent when there is no entitlements file, when it does not mention the
  /// sandbox, or when the sandbox is off: absence of evidence is not a reason
  /// to block a build that would have worked.
  static String? complain(Directory projectDir) {
    final File file = entitlementsFile(projectDir);
    if (!file.existsSync()) return null;
    if (!enablesSandbox(file.readAsStringSync())) return null;
    return message(file.path);
  }

  /// Whether a `.entitlements` plist turns App Sandbox on.
  ///
  /// Deliberately not a full plist parser. The question is narrow -- does this
  /// one key say true -- and the file is generated by Xcode, so the shape is
  /// known. Comments are stripped first, because the entitlements files people
  /// write are heavily commented and a `<true/>` inside a comment is exactly
  /// the sort of thing that would make this lie.
  static bool enablesSandbox(String plist) {
    final String stripped = plist.replaceAll(
      RegExp(r'<!--.*?-->', dotAll: true),
      '',
    );
    final int key = stripped.indexOf('com.apple.security.app-sandbox');
    if (key < 0) return false;
    final Match? value = RegExp(
      r'<(true|false)\s*/>',
    ).firstMatch(stripped.substring(key));
    return value?.group(1) == 'true';
  }

  /// [plist] with App Sandbox turned off, or null if it already is.
  ///
  /// Only the one key, and only its value: an entitlements file is a security
  /// document, and rewriting more of it than was asked for is not a service.
  static String? withSandboxDisabled(String plist) {
    final Match? key =
        RegExp('<key>com.apple.security.app-sandbox</key>').firstMatch(plist);
    if (key == null) return null;
    final Match? value =
        RegExp(r'<true\s*/>').matchAsPrefix(plist, key.end) ??
            RegExp(r'\s*<true\s*/>').matchAsPrefix(plist, key.end);
    if (value == null) return null;
    return plist.replaceRange(
      value.start,
      value.end,
      value.group(0)!.replaceFirst(RegExp(r'<true\s*/>'), '<false/>'),
    );
  }

  static String message(String path) =>
      'This app is sandboxed, and the render host is a macOS build of it.\n'
      '\n'
      '$path\n'
      'sets com.apple.security.app-sandbox to <true/>, and the host is signed\n'
      'with it. App Sandbox forbids running a binary outside the app\n'
      'bundle, so the host cannot reach ffmpeg: the render would build for as\n'
      'long as your app takes to build and then fail at the encode step with\n'
      '"Operation not permitted".\n'
      '\n'
      'The host is a developer tool and is never distributed, so it is safe to\n'
      'build it without the sandbox:\n'
      '\n'
      '  reelforge init --fix-entitlements\n'
      '\n'
      'which sets that one key to <false/> and touches nothing else. Put it\n'
      'back before you ship: an app distributed through the Mac App Store has\n'
      'to be sandboxed. Giving the host its own build configuration with its\n'
      'own entitlements avoids the round trip entirely.\n'
      '\n'
      'Pass --allow-sandbox to build anyway -- correct if the host reaches\n'
      'ffmpeg some other way, such as a copy inside the bundle.';
}
